[package]
name = "eth-valkyoth-evm-core"
description = "Default dependency-free no_std Ethereum EVM core domains for eth."
version = "0.29.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
readme = "README.md"

[features]
default = []
alloc = ["dep:eth-valkyoth-sanitization"]
std = ["alloc"]
testing = []

[dependencies]
eth-valkyoth-sanitization = { workspace = true, optional = true }

[dev-dependencies]
num-bigint.workspace = true

[lints]
workspace = true

[[example]]
name = "access_tracker_benchmark"
required-features = ["std"]

[[example]]
name = "precompile_contract_benchmark"
required-features = ["std"]
